#index:
#    path: /
#    controller: App\Controller\DefaultController::index

dicetosser:
    path: /dicetosser
    controller: App\Controller\DiceGameController::tossDice
    methods: [GET]

yatzystart:
    path: /yatzystart
    controller: App\Controller\YatzyGameController::showStartGame
    methods: [GET]

yatzy:
    path: /yatzy
    controller: App\Controller\YatzyGameController::showGame
    methods: [POST]
    